#!/system/bin/sh
# Script to launch frandom at boot by Ryuinferno @ XDA

chmod 644 /dev/frandom
chmod 644 /dev/erandom

FRANDOM="/dev/frandom"
ERANDOM="/dev/erandom"

if [ -c "$FRANDOM" ]; then
  mv /dev/random /dev/random.ori
  ln -s /dev/frandom /dev/random
  chmod 644 /dev/random
fi

if [ -c "$ERANDOM" ]; then
  mv /dev/urandom /dev/urandom.ori
  ln -s /dev/erandom /dev/urandom
  chmod 644 /dev/urandom
fi